cmake:
  - '(cmake|CMake)'
meson:
  - '(meson|Meson)'
windows:
  - '(windows|Windows)'
darwin:
  - '(macos|darwin|macOS|Darwin)'
linux:
  - '(linux|Linux)'
runtime:
  - '(segmentation fault|abort trap|segfault|runtime)'
