name: Bug report
description: Report something that went wrong
title: "[Brief description of bug]"
labels: bug
assignees: aarikpokras

body:
 - type: textarea
   attributes:
     label: Bug summary
     description: Describe what happened
   validations:
     required: true
 - type: dropdown
   attributes:
     multiple: true
     options:
       - Compilation with CMake
       - Compilation with Meson
       - Runtime
       - Segmentation fault
       - Abort trap
     label: Step of use
     description: If the step isn't here, please list it in the Bug Summary field.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Steps to reproduce
     description: Describe how to reproduce the bug.
   validations:
     required: true
 - type: textarea
   attributes:
     label: Expected behavior
     description: What was supposed to happen?
   validations:
     required: true
 - type: textarea
   attributes:
     label: Screenshots
     description: Are there screenshots that show the bug?
   validations:
     required: false
 - type: markdown
   attributes:
     value: Thank you!
