name: "Create release"
on:
  push:
    tags:
      - v*.*.*

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Make release
        uses: actions/checkout@v4
      - run: |
         gh release create ${{ github.ref_name }} -t "EBSL ${{ github.ref_name }}" -R aarikpokras/ebsl -F inter-changelog.md
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
