name: "Create release"
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
         gh release create ${{ github.ref_name }} -t "EBSL ${{ github.ref_name }}" -R aarikpokras/ebsl
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
